### ISSUE TITLE
Resume Generator Web app using JavaScript

### ISSUE THREAD

**Issue by Rishikavishnoi** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#106]
Resume generator web application that helps to build a resume 
### Working 
- Fill the form
- Click to Generate Resume
- Click to print and Download it

**Comment by Rishikavishnoi** [comment]
@KhushbooGupta2111  assign to me

**Comment by hiferli** [comment]
Thank you for adding your project :)
