### ISSUE TITLE
Full stack project

### ISSUE THREAD

**Issue by anamikarawat** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#14]
I want to add a full stack project called stackover-clone but its in under process not fully cumpleted yet

**Comment by hiferli** [comment]
Sure go ahead.
Please do add a README stating the places where you want improvements in the project.

**Comment by SJ-Kumar** [comment]
Planning to add a frontend login validation page. Please assign.

**Comment by KhushbooGupta2111** [comment]
@SJ-Kumar, you have been assigned. 
@anamikarawat, if you have suggestions, please leave your comments.

**Comment by SJ-Kumar** [comment]
Sure, Thank you

**Comment by hiferli** [comment]
@anamikarawat Added files in the project.
@SJ-Kumar If you have any changes/modifications in the project then please go ahead with the same

**Comment by anamikarawat** [comment]
first go through the project and if you want any modification and able to do so then go ahead and please create a new  issue for that @SJ-Kumar

**Comment by hiferli** [comment]
Thank You @anamikarawat for the contribution :)
