### ISSUE TITLE
Wrong directory 

### ISSUE THREAD

**Issue by KhushbooGupta2111** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#29]
@s-k-jha , please add the oasis project 3 inside the frontend under the web development directory.

**Comment by jotasprout** [comment]
If I understand this correctly, please assign this to me. You just need the **oasis project 3** folder moved into the  **web development** folder?

**Comment by KhushbooGupta2111** [comment]
Yes, you have to move this under the frontend directory inside the web development folder. I have assigned this to you.

**Comment by jotasprout** [comment]
Thank you! I'm on it!

**Comment by hiferli** [comment]
Thank you for doing the changes as mentioned @jotasprout

**Comment by s-k-jha** [comment]
@KhushbooGupta2111 issue solved or not?? for wrong directory
