### ISSUE TITLE
Text Editor 

### ISSUE THREAD

**Issue by Rishikavishnoi** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#41]
Build a text editor using HTML ,CSS , JAVASCRIPT

<img width="956" alt="preview (2)" src="https://user-images.githubusercontent.com/84177590/194722685-e9177ac0-72ed-441c-b9e5-83aa0614d5a2.png">

**Comment by Rishikavishnoi** [comment]
@hiferli assign it to me

**Comment by KhushbooGupta2111** [comment]
You have been assigned this issue

**Comment by Rishikavishnoi** [comment]
@KhushbooGupta2111  okay thanks
