### ISSUE TITLE
Want to add my Drum kit project.

### ISSUE THREAD

**Issue by shivdeep0712** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#47]
I want to add my project in front-end folder. Please assign me this issue with hactoberfest label.

**Comment by hiferli** [comment]
Sure go ahead :)

**Comment by AayushiSingh005** [comment]
Plz assign me also.

**Comment by Ankur-Sh** [comment]
pls assign it to me @hiferli

**Comment by KhushbooGupta2111** [comment]
@AayushiSingh005 and @Ankur-Sh , sure we will but please raise separate issues or even you send pull request too

**Comment by hiferli** [comment]
@shivdeep0712 has added the Drumkit project.
@AayushiSingh005 and @Ankur-Sh if you want to contribute to @shivdeep0712 's project then please raise separate issues for the same.
Otherwise if you want to add your projects then please make separate PRs for the same

Thanks
