### ISSUE TITLE
Want to add my project Dice game.

### ISSUE THREAD

**Issue by shivdeep0712** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#48]
I want to add my project in front-end folder. Please assign me this issue with hactoberfest label.

**Comment by hiferli** [comment]
Sure :)

**Comment by AayushiSingh005** [comment]
I also want to add my project  . Please assign me this issue with hactoberfest label.

**Comment by Ankur-Sh** [comment]
pls assign it to me @hiferli

**Comment by hiferli** [comment]
@AayushiSingh005 and @Ankur-Sh 
Please raise a separate issue regarding your projects.
In case you have the similar project, then please do rename the folder structure to avoid overlapping.
You can rename it like <Project-Name>-<Your-Name>

**Comment by hiferli** [comment]
Also in a case where you want to contribute in @shivdeep0712 's project then do comment and let me know

**Comment by Ankur-Sh** [comment]
send my PR pls accept it @hiferli

**Comment by hiferli** [comment]
@shivdeep0712 has added the Drumkit project.
@AayushiSingh005 and @Ankur-Sh if you want to contribute to @shivdeep0712 's project then please raise separate issues for the same.
Otherwise if you want to add your projects then please make separate PRs for the same

Thanks
