### ISSUE TITLE
RawTemplate Android App

### ISSUE THREAD

**Issue by binayshaw7777** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#68]
I would like to submit a pre-developed android app (Kotlin) consisting of screens like:

1 Splash screen
2 Onboarding Screen
3 SignUp
4 SignIn
5 Forgot Password
6 Homescreen (with Bottom navigation bar)

This will make the development process easy and will also save a lot of time.
Please approve. Also, this was a collaborative project where @aritra-tech was involved. Can you please assign him too? We both share equal credit to the app.

**Comment by KhushbooGupta2111** [comment]
@binayshaw7777, thanks for your contribution, we will assign it to @aritra-tech as well. For that please tell him to comment here.

**Comment by aritra-tech** [comment]
Yes, @KhushbooGupta2111 please assign it to me

**Comment by hiferli** [comment]
Thank you for contributing :)
