### ISSUE TITLE
Code Editor using JS 

### ISSUE THREAD

**Issue by Rishikavishnoi** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#77]
Building an code editor using HTML , CSS, JAVASCRIPRT

**Comment by Rishikavishnoi** [comment]
@KhushbooGupta2111 assign it to me

**Comment by KhushbooGupta2111** [comment]
Yeah, I have assigned it to you. Go ahead.

**Comment by srini-vasan-c** [comment]
If still any changes needed, pls assign to me. I am interested

**Comment by KhushbooGupta2111** [comment]
@Rishikavishnoi, if you wish some changes to be made, kindly mention them.
@srini-vasan-c, if you have some ideas and some improvments to make, mention them then I will assign it you.

**Comment by srini-vasan-c** [comment]
@KhushbooGupta2111  We can add dark/light theme, tabs section for html, css, js section.

**Comment by KhushbooGupta2111** [comment]
@srini-vasan-c, so if you are confident with it and ready to contribute, let me know, I will assign you this issue.

**Comment by srini-vasan-c** [comment]
Yes please, I am ready to contribute

**Comment by Rishikavishnoi** [comment]
@srini-vasan-c  if you want to add more functionality then raise another issue, and @KhushbooGupta2111  will assign that to you.

**Comment by Rishikavishnoi** [comment]
@KhushbooGupta2111 but I  have done my work, my PR got merged but still this issue is not closed and you didn't add a label in my PR ... Please add a label if you merge the PR and close my issue also.

**Comment by KhushbooGupta2111** [comment]
@srini-vasan-c, you can raise another issue, I will assign you.
@Rishikavishnoi, I will close this issue and will add the label.

**Comment by Rishikavishnoi** [comment]
@KhushbooGupta2111 I think you have to add hacktoberfest-accepted label in PR not in the issue ...please check it once to the rule  ...as in my PR there is no label as accepted so may be it will not add  accepted in hacktoberfest after review it
