### ISSUE TITLE
Add an Analog Clock

### ISSUE THREAD

**Issue by srini-vasan-c** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#87]
Add an Analog Clock by using HTML,CSS, javascript

**Comment by srini-vasan-c** [comment]
@KhushbooGupta2111 pls check and assign me

**Comment by srini-vasan-c** [comment]
@KhushbooGupta2111 Pls let me know if you have any features that to be implemented, I am ready to work on it. Thanks

**Comment by KhushbooGupta2111** [comment]
@srini-vasan-c, there are already projects related to it, I would suggest you t go and check them and point out the differences in your and their projects. Also, I will assign this to you and make a PR and  I will see your code. But before that please ensure you are making an unique contribution.

**Comment by srini-vasan-c** [comment]
@KhushbooGupta2111 pls add hacktoberfest label and related items, so that it will be counted for event

**Comment by Vartika123456** [comment]
@srini-vasan-c, I would like to work on this issue please assign this issue to me

**Comment by hiferli** [comment]
Hey @Vartika123456 
@srini-vasan-c is working on the project and as soon as he has pushed his code you can create another issue to make changes and improvements in the same.

Thanks

**Comment by Priya1511jain** [comment]
can you assign this issue to me .
