### ISSUE TITLE
add a website of news

### ISSUE THREAD

**Issue by mpatwa98** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#88]
I want to add a react project NewsMonkey. It is a react based frontend project. It uses newsAPI to fetch news. I used react, bootstrap, and javascript too create it. I made it with help of codewithharry youtube channel.

**Comment by hiferli** [comment]
Sure go ahead!

**Comment by mpatwa98** [comment]
I have made a pull request #96 please it and merge if you find it good

**Comment by hiferli** [comment]
Thank you for adding your project :)
