### ISSUE TITLE
Git-Automation-Script

### ISSUE THREAD

**Issue by PIYUSH-MISHRA-00** [GDSC-BPIT/GDSC-BPIT-Hacktober-Fest-2022#89]
hay @KhushbooGupta2111 I want to add a menu driven git automation script for automating git with one time configuration under can you assign me under a Hacktoberfest label???

**Comment by KhushbooGupta2111** [comment]
Sure, go ahead.

**Comment by hiferli** [comment]
Thank you for adding your project :)
